In [5]:
#Programa de eliminación Gaussiana mostrando los pasos
import numpy as np

a = np.array([[1.0, 2.0, 4.0], [1.0, 3.0, 9.0], [1.0, 4.0, 16.0]])
print('La matriz de coeficientes es:\n ', a)
b = np.array([[5.0], [0.0], [20.0]])
n = len(b)
print('La matriz constante es:\n ', b)

matriz_aumentada = np.concatenate((a,b), axis=1, dtype=float)
print('La matriz aumentada es :\n', matriz_aumentada)


def gaussElimin(a,b):
  # Fase de eliminacion
  for k in range(0,n-1):
    for i in range(k+1,n):
      if matriz_aumentada[i,k] != 0.0:
        lam = matriz_aumentada[i,k]/matriz_aumentada[k,k]
        matriz_aumentada[i] = matriz_aumentada[i] - lam*matriz_aumentada[k]
        b[i] = b[i] - lam*b[k]
        print(f'El siguiente elemento del procedimiento es: {'\n'}{matriz_aumentada}')
  # Fase de sustitucion hacia atras
  for k in range(n-1,-1,-1):
    b[k] = (b[k] - np.dot(matriz_aumentada[k,k+1:n],b[k+1:n]))/matriz_aumentada[k,k]
  return b


print('El vector solución es :\n',gaussElimin(a,b))

La matriz de coeficientes es:
  [[ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  4. 16.]]
La matriz constante es:
  [[ 5.]
 [ 0.]
 [20.]]
La matriz aumentada es :
 [[ 1.  2.  4.  5.]
 [ 1.  3.  9.  0.]
 [ 1.  4. 16. 20.]]
El siguiente elemento del procedimiento es: 
[[ 1.  2.  4.  5.]
 [ 0.  1.  5. -5.]
 [ 1.  4. 16. 20.]]
El siguiente elemento del procedimiento es: 
[[ 1.  2.  4.  5.]
 [ 0.  1.  5. -5.]
 [ 0.  2. 12. 15.]]
El siguiente elemento del procedimiento es: 
[[ 1.  2.  4.  5.]
 [ 0.  1.  5. -5.]
 [ 0.  0.  2. 25.]]
El vector solución es :
 [[ 90. ]
 [-67.5]
 [ 12.5]]


In [6]:
#Programa de eliminación Gaussiana mostrando los pasos
import numpy as np

a = np.array([[2.0, 3.0, 2.0], [1.0, 3.0, 2.0], [1.0, 1.0, 1.0]])
print('La matriz de coeficientes es:\n ', a)
b = np.array([[27.0], [22.0], [12.0]])
n = len(b)
print('La matriz constante es:\n ', b)

matriz_aumentada = np.concatenate((a,b), axis=1, dtype=float)
print('La matriz aumentada es :\n', matriz_aumentada)


def gaussElimin(a,b):
  # Fase de eliminacion
  for k in range(0,n-1):
    for i in range(k+1,n):
      if matriz_aumentada[i,k] != 0.0:
        lam = matriz_aumentada[i,k]/matriz_aumentada[k,k]
        matriz_aumentada[i] = matriz_aumentada[i] - lam*matriz_aumentada[k]
        b[i] = b[i] - lam*b[k]
        print(f'El siguiente elemento del procedimiento es: {'\n'}{matriz_aumentada}')
  # Fase de sustitucion hacia atras
  for k in range(n-1,-1,-1):
    b[k] = (b[k] - np.dot(matriz_aumentada[k,k+1:n],b[k+1:n]))/matriz_aumentada[k,k]
  return b


print('El vector solución es :\n',gaussElimin(a,b))

La matriz de coeficientes es:
  [[2. 3. 2.]
 [1. 3. 2.]
 [1. 1. 1.]]
La matriz constante es:
  [[27.]
 [22.]
 [12.]]
La matriz aumentada es :
 [[ 2.  3.  2. 27.]
 [ 1.  3.  2. 22.]
 [ 1.  1.  1. 12.]]
El siguiente elemento del procedimiento es: 
[[ 2.   3.   2.  27. ]
 [ 0.   1.5  1.   8.5]
 [ 1.   1.   1.  12. ]]
El siguiente elemento del procedimiento es: 
[[ 2.   3.   2.  27. ]
 [ 0.   1.5  1.   8.5]
 [ 0.  -0.5  0.  -1.5]]
El siguiente elemento del procedimiento es: 
[[ 2.          3.          2.         27.        ]
 [ 0.          1.5         1.          8.5       ]
 [ 0.          0.          0.33333333  1.33333333]]
El vector solución es :
 [[5.]
 [3.]
 [4.]]
