In [37]:
#Programa de eliminación Gaussiana mostrando los pasos
import numpy as np

a = np.array([[1.0, 0.0, -3.0], [3.0, 1.0, -2.0], [2.0, 2.0, 1.0]])
print('La matriz de coeficientes es:\n ', a)
b = np.array([[-2.0], [5.0], [4.0]])
n = len(b)
print('La matriz constante es:\n ', b)

matriz_aumentada = np.concatenate((a,b), axis=1, dtype=float)
print('La matriz aumentada es :\n', matriz_aumentada)


def gaussElimin(a,b):
  # Fase de eliminacion
  for k in range(0,n-1):
    for i in range(k+1,n):
      if matriz_aumentada[i,k] != 0.0:
        lam = matriz_aumentada[i,k]/matriz_aumentada[k,k]
        matriz_aumentada[i] = matriz_aumentada[i] - lam*matriz_aumentada[k]
        b[i] = b[i] - lam*b[k]
        print(f'El siguiente elemento del procedimiento es: {'\n'}{matriz_aumentada}')
  # Fase de sustitucion hacia atras
  for k in range(n-1,-1,-1):
    b[k] = (b[k] - np.dot(matriz_aumentada[k,k+1:n],b[k+1:n]))/matriz_aumentada[k,k]
  return b


print('El vector solución es :\n',gaussElimin(a,b))

La matriz de coeficientes es:
  [[ 1.  0. -3.]
 [ 3.  1. -2.]
 [ 2.  2.  1.]]
La matriz constante es:
  [[-2.]
 [ 5.]
 [ 4.]]
La matriz aumentada es :
 [[ 1.  0. -3. -2.]
 [ 3.  1. -2.  5.]
 [ 2.  2.  1.  4.]]
El siguiente elemento del procedimiento es: 
[[ 1.  0. -3. -2.]
 [ 0.  1.  7. 11.]
 [ 2.  2.  1.  4.]]
El siguiente elemento del procedimiento es: 
[[ 1.  0. -3. -2.]
 [ 0.  1.  7. 11.]
 [ 0.  2.  7.  8.]]
El siguiente elemento del procedimiento es: 
[[  1.   0.  -3.  -2.]
 [  0.   1.   7.  11.]
 [  0.   0.  -7. -14.]]
El vector solución es :
 [[ 4.]
 [-3.]
 [ 2.]]
